/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as auAContractSol from "./AuAContract.sol";
export type { auAContractSol };
import type * as nftContractSol from "./NFTContract.sol";
export type { nftContractSol };
import type * as auctionContractSol from "./auctionContract.sol";
export type { auctionContractSol };
